//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDD
    {
        public int ID { get; set; }
        public string TENDIADIEM { get; set; }
        public int IDDD { get; set; }
        public string MATP { get; set; }
        public string TENTP_NUOC { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
    }
}
