//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATTOUR
    {
        public int ID { get; set; }
        public int IDKH { get; set; }
        public int IDDOAN { get; set; }
    
        public virtual DOAN DOAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
