//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIATOUR
    {
        public int ID { get; set; }
        public int GIA { get; set; }
        public int IDTOUR { get; set; }
        public string THANGBD { get; set; }
        public string THANGKT { get; set; }
        public bool current { get; set; }
    
        public virtual TOUR TOUR { get; set; }
    }
}
