//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.DOANs = new HashSet<DOAN>();
        }
    
        public int ID { get; set; }
        public string TENTOUR { get; set; }
        public int IDDIADIEM { get; set; }
        public string DACDIEM { get; set; }
        public int GIATOUR { get; set; }
        public string LOAIHINH { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOAN> DOANs { get; set; }
    }
}
